// Constants that might be tweaked in alternate implementations
var MAX_TERMS = 7;
var TERM_LENGTH = 4;
var INTERRUPTED_TERM_LENGTH = 2;
var QUALIFICATION_DM_PER_PREVIOUS_CAREER = -2;

var humanSTR = {name:"Strength",abbrev:"STR",dice:2,mod:0,afterDash:false,max:15};
var humanDEX = {name:"Dexterity",abbrev:"DEX",dice:2,mod:0,afterDash:false,max:15};
var humanEND = {name:"Endurance",abbrev:"END",dice:2,mod:0,afterDash:false,max:15};
var humanINT = {name:"Intelligence",abbrev:"INT",dice:2,mod:0,afterDash:false,max:15};
var humanEDU = {name:"Education",abbrev:"EDU",dice:2,mod:0,afterDash:false,max:15};
var humanSOC = {name:"Social Standing",abbrev:"SOC",dice:2,mod:0,afterDash:false,max:15};
var humanUPPData = [ humanSTR, humanDEX, humanEND, humanINT, humanEDU, humanSOC ];

var esperPSI = {name:"Psionic Strength",abbrev:"PSI",dice:2,mod:0,afterDash:true,max:12};
var esperUPPData = [ humanSTR, humanDEX, humanEND, humanINT, humanEDU, humanSOC, esperPSI ];

var avianSTR = {name:"Strength",abbrev:"STR",dice:1,mod:0,afterDash:false,max:9};
var avianDEX = {name:"Dexterity",abbrev:"DEX",dice:3,mod:0,afterDash:false,max:21};
var avianEND = {name:"Endurance",abbrev:"END",dice:1,mod:0,afterDash:false,max:9};
var avianUPPData = [ avianSTR, avianDEX, avianEND, humanINT, humanEDU, humanSOC ];

var insectanDEX = {name:"Dexterity",abbrev:"DEX",dice:2,mod:2,afterDash:false,max:17};
var insectanUPPData = [ humanSTR, insectanDEX, humanEND, humanINT, humanEDU, humanSOC ];

var reptilianSTR = {name:"Strength",abbrev:"STR",dice:2,mod:1,afterDash:false,max:16};
var reptilianDEX = {name:"Dexterity",abbrev:"DEX",dice:2,mod:1,afterDash:false,max:16};
var reptilianEND = {name:"Endurance",abbrev:"END",dice:2,mod:-2,afterDash:false,max:10};
var reptilianUPPData = [reptilianSTR, reptilianDEX, reptilianEND, humanINT, humanEDU, humanSOC];

// decision class global variables 
var careerChoice, failedQualificationChoice, injuryCrisisChoice, postCareerDecision, endOfTermDecision, backgroundSkillsChoice, weaponBenefitChoice, weaponChoiceifHaveWeapon, skillTableChoice, benefitTableChoice;
var	animalsCascadeChoice, sciencesCascadeChoice, gunCombatChoice, gunneryChoice, meleeCombatChoice, vehicleChoice, aircraftChoice, watercraftChoice;

// cascade skill tables showing which skills are available for each cascade skill
var	AnimalsCascade = { name:"Animals", choices:["Farming","Riding","Survival","Veterinary Medicine"] };
var	SciencesCascade = { name: "Sciences", choices:["Life Sciences","Physical Sciences","Social Sciences","Space Sciences"] };
var	GunCombatCascade = { name: "Gun Combat", choices:["Archery","Energy Pistol","Energy Rifle","Shotgun","Slug Pistol","Slug Rifle"] };
var	GunneryCascade = { name: "Gunnery", choices:["Bay Weapons","Heavy Weapons","Screens","Spinal Mounts","Turret Weapons"] };
var	MeleeCascade = { name: "Melee Combat", choices:["Bludgeoning Weapons","Natural Weapons","Piercing Weapons","Slashing Weapons"] };
var	VehicleCascade = { name: "Vehicle", choices:["Aircraft","Mole","Tracked Vehicle","Watercraft","Wheeled Vehicle"] };
var	AircraftCascade = { name: "Aircraft", choices:["Grav Vehicle","Rotor Aircraft","Winged Aircraft"] };
var	WatercraftCascade = { name: "Watercraft", choices:["Motorboats","Ocean Ships","Sailing Ships","Submarine"] };

var CascadeLibrary;
var CascadeDecisionObjects;

/* Career Data
Template
var careerObject = 	{ name:"", description:"", qualChar:"", qualTarget:0, surviveChar:"", surviveTarget:0, 
					 commissionChar:"", commissionTarget:0, advanceChar:"", advanceTarget:0, reenlist:0, 
					 ranks:["","","","","","",""], 
					 rankSkills:["","","","","","",""],
					 benefits:["","","","","","",""], 
					 cash:[0,0,0,0,0,0,0], 
					 personalDev:["","","","","",""], 
					 service:["","","","","",""],
					 specialist:["","","","","",""], 
					 advEdu:["","","","","",""],
					 medicalBills:[0.50, 0.75, 1]
					};
*/
var athlete = { name:"Athlete", description:"Athletics", qualChar:"END", qualTarget:8, surviveChar:"DEX", surviveTarget:5, commissionChar:"", commissionTarget:0, advanceChar:"", advanceTarget:0, reenlist:6, ranks:["Athlete","","","","","",""], rankSkills:["Athletics","","","","","",""], benefits:["Low Passage","+1 INT","Weapon","High Passage","Explorers' Society","High Passage",""], cash:[2000,10000,20000,20000,50000,100000,100000], personalDev:["+1 DEX","+1 INT","+1 EDU","+1 SOC","Carousing","Melee Combat"], service:["Athletics","Admin","Carousing","Computer","Gambling","Vehicle"], specialist:["Zero-G","Athletics","Athletics","Computer","Leadership","Gambling"], advEdu:["Advocate","Computer","Liaison","Linguistics","Medicine","Sciences"], medicalBills:[0.50, 0.75, 1] };
var aerospaceDef = { name:"Aerospace Defense", description:"the Aerospace Defense Service", qualChar:"END", qualTarget:5, surviveChar:"DEX", surviveTarget:5, commissionChar:"EDU", commissionTarget:6, advanceChar:"EDU", advanceTarget:7, reenlist:5, ranks:["Airman","Flight Officer","Flight Lieutenant","Squadron Leader","Wing Commander","Group Captain","Air Commodore"], rankSkills:["Aircraft","","","Leader","","",""], benefits:["Low Passage","+1 EDU","Weapon","Mid Passage","Weapon","High Passage","+1 SOC"], cash:[1000,5000,10000,10000,20000,50000,50000], personalDev:["+1 STR","+1 DEX","+1 END","Athletics","Melee Combat","Vehicle"], service:["Electronics","Gun Combat","Gunnery","Melee Combat","Survival","Aircraft"], specialist:["Comms","Gravitics","Gun Combat","Gunnery","Recon","Piloting"], advEdu:["Advocate","Computer","Jack o' Trades","Medicine","Leadership","Tactics"], medicalBills:[0.75, 1, 1] };
var agent = { name:"Agent", description:"the Agency", qualChar:"END", qualTarget:5, surviveChar:"DEX", surviveTarget:5, commissionChar:"EDU", commissionTarget:7, advanceChar:"EDU", advanceTarget:6, reenlist:5, ranks:["Agent","Special Agent","Special Agent in Charge","Unit Chief","Section Chief","Assistant Director","Director"], rankSkills:["Streetwise","","","","Admin","",""], benefits:["Low Passage","+1 INT","Weapon","Mid Passage","+1 SOC","High Passage","Explorers' Society"], cash:[1000,5000,10000,10000,20000,50000,50000], personalDev:["+1 DEX","+1 END","+1 INT","+1 EDU","Athletics","Carousing"], service:["Admin","Computer","Streetwise","Bribery","Leadership","Vehicle"], specialist:["Gun Combat","Melee Combat","Bribery","Leadership","Recon","Survival"], advEdu:["Advocate","Computer","Liaison","Linguistics","Medicine","Leadership"], medicalBills:[0.50, 0.75, 1] };
var barbarian = { name:"Barbarian", description:"the Barbarians", qualChar:"END", qualTarget:5, surviveChar:"STR", surviveTarget:6, commissionChar:"", commissionTarget:0, advanceChar:"", advanceTarget:0, reenlist:5, ranks:["Barbarian","","","","","",""], rankSkills:["Melee Combat","","","","","",""], benefits:["Low Passage","+1 INT","Weapon","Weapon","+1 END","Mid Passage",""], cash:[0,1000,2000,5000,5000,10000,10000], personalDev:["+1 STR","+1 DEX","+1 END","+1 INT","Athletics","Gun Combat"], service:["Mechanics","Gun Combat","Melee Combat","Recon","Survival","Animals"], specialist:["Gun Combat","Jack o' Trades","Melee Combat","Recon","Animals","Tactics"], advEdu:["Advocate","Linguistics","Medicine","Leadership","Tactics","Broker"], medicalBills:[0, 0.5, 0.75] };
var belter = { name:"Belter", description:"the Belters", qualChar:"INT", qualTarget:4, surviveChar:"DEX", surviveTarget:7, commissionChar:"", commissionTarget:0, advanceChar:"", advanceTarget:0, reenlist:5, ranks:["Belter","","","","","",""], rankSkills:["Zero-G","","","","","",""], benefits:["Low Passage","+1 INT","Weapon","Mid Passage","Ship Shares","High Passage",""], cash:[1000,5000,5000,5000,10000,20000,50000], personalDev:["+1 STR","+1 DEX","+1 END","Zero-G","Melee Combat","Gambling"], service:["Comms","Demolitions","Gun Combat","Gunnery","Prospecting","Piloting"], specialist:["Zero-G","Computer","Electronics","Prospecting","Sciences","Vehicle"], advEdu:["Advocate","Engineering","Medicine","Navigation","Comms","Tactics"], medicalBills:[0, 0.5, 0.75] };
var bureaucrat = { name:"Bureaucrat", description:"the Bureaucracy", qualChar:"SOC", qualTarget:6, surviveChar:"EDU", surviveTarget:4, commissionChar:"SOC", commissionTarget:5, advanceChar:"INT", advanceTarget:8, reenlist:5, ranks:["Assistant","Clerk","Supervisor","Manager","Chief","Director","Minister"], rankSkills:["Admin","","","","Advocate","",""], benefits:["Low Passage","+1 EDU","+1 INT","Mid Passage","Mid Passage","High Passage","+1 SOC"], cash:[1000,5000,10000,10000,20000,50000,50000], personalDev:["+1 DEX","+1 END","+1 INT","+1 EDU","Athletics","Carousing"], service:["Admin","Computer","Carousing","Bribery","Leadership","Vehicle"], specialist:["Admin","Computer","Perception","Leadership","Steward","Vehicle"], advEdu:["Advocate","Computer","Liaison","Linguistics","Medicine","Admin"], medicalBills:[0.50, 0.75, 1] };
var colonist = { name:"Colonist", description:"the Colony", qualChar:"END", qualTarget:5, surviveChar:"END", surviveTarget:6, commissionChar:"INT", commissionTarget:7, advanceChar:"EDU", advanceTarget:6, reenlist:5, ranks:["Citizen","District Leader","District Delegate","Council Adviser","Councilor","Lieutenant Governor","Governor"], rankSkills:["Survival","","","Liaison","","",""], benefits:["Low Passage","+1 INT","Weapon","Mid Passage","Mid Passage","High Passage","+1 SOC"], cash:[1000,5000,5000,5000,10000,20000,50000], personalDev:["+1 STR","+1 DEX","+1 END","+1 INT","Athletics","Gun Combat"], service:["Mechanics","Gun Combat","Animals","Electronics","Survival","Vehicle"], specialist:["Athletics","Carousing","Jack o' Trades","Engineering","Animals","Vehicle"], advEdu:["Advocate","Linguistics","Medicine","Liaison","Admin","Animals"], medicalBills:[0, 0.5, 0.75] };
var diplomat = { name:"Diplomat", description:"the Diplomacy Service", qualChar:"SOC", qualTarget:6, surviveChar:"EDU", surviveTarget:5, commissionChar:"INT", commissionTarget:7, advanceChar:"SOC", advanceTarget:7, reenlist:5, ranks:["Attache","Third Secretary","Second Secretary","First Secretary","Counselor","Minister","Ambassador"], rankSkills:["Liaison","","","Admin","","",""], benefits:["Low Passage","+1 EDU","Mid Passage","High Passage","+1 SOC","High Passage","Explorers' Society"], cash:[1000,5000,10000,20000,20000,50000,100000], personalDev:["+1 DEX","+1 END","+1 INT","+1 EDU","Athletics","Carousing"], service:["Admin","Computer","Carousing","Bribery","Liaison","Vehicle"], specialist:["Carousing","Linguistics","Bribery","Liaison","Steward","Vehicle"], advEdu:["Advocate","Computer","Liaison","Linguistics","Medicine","Leadership"], medicalBills:[0.50, 0.75, 1] };
var drifter = { name:"Drifter", description:"the Drifting Life", qualChar:"DEX", qualTarget:5, surviveChar:"END", surviveTarget:5, commissionChar:"", commissionTarget:0, advanceChar:"", advanceTarget:0, reenlist:5, ranks:["","","","","","",""], rankSkills:["","","","","","",""], benefits:["Low Passage","+1 INT","Weapon","Weapon","Mid Passage","Mid Passage",""], cash:[0,1000,2000,5000,5000,10000,10000], personalDev:["+1 STR","+1 DEX","+1 END","Melee Combat","Bribery","Gambling"], service:["Streetwise","Mechanics","Gun Combat","Melee Combat","Recon","Vehicle"], specialist:["Electronics","Melee Combat","Bribery","Streetwise","Gambling","Recon"], advEdu:["Computer","Engineering","Jack o' Trades","Medicine","Liaison","Tactics"], medicalBills:[0, 0.5, 0.75] };
var entertainer = { name:"Entertainer", description:"the Entertainment Industry", qualChar:"SOC", qualTarget:8, surviveChar:"INT", surviveTarget:4, commissionChar:"", commissionTarget:0, advanceChar:"", advanceTarget:0, reenlist:6, ranks:["Entertainer","","","","","",""], rankSkills:["Carousing","","","","","",""], benefits:["Low Passage","+1 EDU","+1 SOC","High Passage","Ship Shares","High Passage",""], cash:[2000,10000,20000,20000,50000,100000,100000], personalDev:["+1 DEX","+1 INT","+1 EDU","+1 SOC","Carousing","Melee Combat"], service:["Athletics","Admin","Carousing","Bribery","Gambling","Vehicle"], specialist:["Computer","Carousing","Bribery","Liaison","Gambling","Recon"], advEdu:["Advocate","Computer","Carousing","Linguistics","Medicine","Sciences"], medicalBills:[0.50, 0.75, 1] };
var hunter = { name:"Hunter", description:"the Hunters", qualChar:"END", qualTarget:5, surviveChar:"STR", surviveTarget:8, commissionChar:"", commissionTarget:0, advanceChar:"", advanceTarget:0, reenlist:6, ranks:["Hunter","","","","","",""], rankSkills:["Survival","","","","","",""], benefits:["Low Passage","+1 INT","Weapon","High Passage","Ship Shares","High Passage",""], cash:[1000,5000,10000,20000,20000,50000,100000], personalDev:["+1 STR","+1 DEX","+1 END","+1 INT","Athletics","Gun Combat"], service:["Mechanics","Gun Combat","Melee Combat","Recon","Survival","Vehicle"], specialist:["Admin","Comms","Electronics","Recon","Animals","Vehicle"], advEdu:["Advocate","Linguistics","Medicine","Liaison","Tactics","Animals"], medicalBills:[0.50, 0.75, 1] };
var marine = { name:"Marine", description:"the Marines", qualChar:"INT", qualTarget:6, surviveChar:"END", surviveTarget:6, commissionChar:"EDU", commissionTarget:6, advanceChar:"SOC", advanceTarget:7, reenlist:6, ranks:["Trooper","Lieutenant","Captain","Major","Lt Colonel","Colonel","Brigadier"], rankSkills:["Zero-G","","","Tactics","","",""], benefits:["Low Passage","+1 EDU","Weapon","Mid Passage","+1 SOC","High Passage","Explorers' Society"], cash:[1000,5000,10000,10000,20000,50000,50000], personalDev:["+1 STR","+1 DEX","+1 END","+1 INT","+1 EDU","Melee Combat"], service:["Comms","Demolitions","Gun Combat","Gunnery","Melee Combat","Battle Dress"], specialist:["Electronics","Gun Combat","Melee Combat","Survival","Recon","Vehicle"], advEdu:["Advocate","Computer","Gravitics","Medicine","Navigation","Tactics"], medicalBills:[0.75, 1, 1] };
var maritimeDef = { name:"Maritime Defense", description:"the Maritime Defense Service", qualChar:"END", qualTarget:5, surviveChar:"END", surviveTarget:5, commissionChar:"INT", commissionTarget:6, advanceChar:"EDU", advanceTarget:7, reenlist:5, ranks:["Seaman","Ensign","Lieutenant","Lt Commander","Commander","Captain","Admiral"], rankSkills:["Watercraft","","","Leadership","","",""], benefits:["Low Passage","+1 EDU","Weapon","Mid Passage","Weapon","High Passage","+1 SOC"], cash:[1000,5000,10000,10000,20000,50000,50000], personalDev:["+1 STR","+1 DEX","+1 END","Athletics","Melee Combat","Vehicle"], service:["Mechanics","Gun Combat","Gunnery","Melee Combat","Survival","Watercraft"], specialist:["Comms","Electronics","Gun Combat","Demolitions","Recon","Watercraft"], advEdu:["Advocate","Computer","Jack o' Trades","Medicine","Leadership","Tactics"], medicalBills:[0.75, 1, 1] };
var mercenary = { name:"Mercenary", description:"the Mercenaries", qualChar:"INT", qualTarget:4, surviveChar:"END", surviveTarget:6, commissionChar:"INT", commissionTarget:7, advanceChar:"INT", advanceTarget:6, reenlist:5, ranks:["Private","Lieutenant","Captain","Major","Lt Colonel","Colonel","Brigadier"], rankSkills:["Gun Combat","","","Tactics","","",""], benefits:["Low Passage","+1 INT","Weapon","High Passage","+1 SOC","High Passage","Ship Shares"], cash:[1000,5000,10000,20000,20000,50000,100000], personalDev:["+1 STR","+1 DEX","+1 END","Zero-G","Melee Combat","Gambling"], service:["Comms","Mechanics","Gun Combat","Melee Combat","Gambling","Battle Dress"], specialist:["Gravitics","Gun Combat","Gunnery","Melee Combat","Recon","Vehicle"], advEdu:["Advocate","Engineering","Medicine","Navigation","Sciences","Tactics"], medicalBills:[0.50, 0.75, 1] };
var merchant = { name:"Merchant", description:"the Merchants", qualChar:"INT", qualTarget:4, surviveChar:"INT", surviveTarget:5, commissionChar:"INT", commissionTarget:5, advanceChar:"EDU", advanceTarget:8, reenlist:4, ranks:["Crewman","Deck Cadet","Fourth Officer","Third Officer","Second Officer","First Officer","Captain"], rankSkills:["Steward","","","Piloting","","",""], benefits:["Low Passage","+1 EDU","Weapon","High Passage","Ship Shares","High Passage","Explorers' Society"], cash:[1000,5000,10000,20000,20000,50000,100000], personalDev:["+1 STR","+1 DEX","+1 END","Zero-G","Melee Combat","Steward"], service:["Comms","Engineering","Gun Combat","Melee Combat","Broker","Vehicle"], specialist:["Carousing","Gunnery","Jack o' Trades","Medicine","Navigation","Piloting"], advEdu:["Advocate","Engineering","Medicine","Navigation","Sciences","Tactics"], medicalBills:[0.50, 0.75, 1] };
var navy = { name:"Navy", description:"the Navy", qualChar:"INT", qualTarget:6, surviveChar:"INT", surviveTarget:5, commissionChar:"SOC", commissionTarget:7, advanceChar:"EDU", advanceTarget:6, reenlist:5, ranks:["Starman","Midshipman","Lieutenant","Lt Commander","Commander","Captain","Commodore"], rankSkills:["Zero-G","","","Tactics","","",""], benefits:["Low Passage","+1 EDU","Weapon","Mid Passage","+1 SOC","High Passage","Explorers' Society"], cash:[1000,5000,10000,10000,20000,50000,50000], personalDev:["+1 STR","+1 DEX","+1 END","+1 INT","+1 EDU","Melee Combat"], service:["Comms","Engineering","Gun Combat","Gunnery","Melee Combat","Vehicle"], specialist:["Gravitics","Jack o' Trades","Melee Combat","Navigation","Leadership","Piloting"], advEdu:["Advocate","Computer","Engineering","Medicine","Navigation","Tactics"], medicalBills:[0.75, 1, 1] };
var noble = { name:"Noble", description:"the Nobility", qualChar:"SOC", qualTarget:8, surviveChar:"SOC", surviveTarget:4, commissionChar:"EDU", commissionTarget:5, advanceChar:"INT", advanceTarget:8, reenlist:6, ranks:["Courtier","Knight","Baron","Marquis","Count","Duke","Archduke"], rankSkills:["Carousing","","","","Advocate","",""], benefits:["High Passage","+1 EDU","+1 INT","High Passage","Explorers' Society","High Passage","Ship Shares"], cash:[2000,10000,20000,20000,50000,100000,100000], personalDev:["+1 DEX","+1 INT","+1 EDU","+1 SOC","Carousing","Melee Combat"], service:["Athletics","Admin","Carousing","Leadership","Gambling","Vehicle"], specialist:["Computer","Carousing","Gun Combat","Melee Combat","Liaison","Animals"], advEdu:["Advocate","Computer","Liaison","Linguistics","Medicine","Sciences"], medicalBills:[0.50, 0.75, 1] };
var physician = { name:"Physician", description:"the Medical Profession", qualChar:"EDU", qualTarget:6, surviveChar:"INT", surviveTarget:4, commissionChar:"INT", commissionTarget:5, advanceChar:"EDU", advanceTarget:8, reenlist:5, ranks:["Intern","Resident","Senior Resident","Chief Resident","Attending Physician","Service Chief","Hospital Administrator"], rankSkills:["Medicine","","","","Admin","",""], benefits:["Low Passage","+1 EDU","+1 INT","High Passage","Explorers' Society","High Passage","+1 SOC"], cash:[2000,10000,20000,20000,50000,100000,100000], personalDev:["+1 STR","+1 DEX","+1 END","+1 INT","+1 EDU","Gun Combat"], service:["Admin","Computer","Mechanics","Medicine","Leadership","Sciences"], specialist:["Computer","Carousing","Electronics","Medicine","Medicine","Sciences"], advEdu:["Advocate","Computer","Jack o' Trades","Linguistics","Medicine","Sciences"], medicalBills:[0.50, 0.75, 1] };
var pirate = { name:"Pirate", description:"the Pirates (arrgh!)", qualChar:"DEX", qualTarget:5, surviveChar:"DEX", surviveTarget:6, commissionChar:"STR", commissionTarget:7, advanceChar:"INT", advanceTarget:6, reenlist:5, ranks:["Crewman","Corporal","Lieutenant","Lt Commander","Commander","Captain","Commodore"], rankSkills:["Gunnery","","Piloting","","","",""], benefits:["Low Passage","+1 INT","Weapon","High Passage","+1 SOC","High Passage","Ship Shares"], cash:[1000,5000,10000,20000,20000,50000,100000], personalDev:["+1 STR","+1 DEX","+1 END","Melee Combat","Bribery","Gambling"], service:["Streetwise","Electronics","Gun Combat","Melee Combat","Recon","Vehicle"], specialist:["Zero-G","Comms","Engineering","Gunnery","Navigation","Piloting"], advEdu:["Computer","Gravitics","Jack o' Trades","Medicine","Advocate","Tactics"], medicalBills:[0.50, 0.75, 1] };
var rogue = { name:"Rogue", description:"being a Rogue", qualChar:"DEX", qualTarget:5, surviveChar:"DEX", surviveTarget:4, commissionChar:"STR", commissionTarget:6, advanceChar:"INT", advanceTarget:7, reenlist:4, ranks:["Independent","Associate","Soldier","Lieutenant","Underboss","Consgliere","Boss"], rankSkills:["Streetwise","","Gun Combat","","","",""], benefits:["Low Passage","+1 INT","Weapon","Mid Passage","Weapon","High Passage","+1 SOC"], cash:[1000,5000,5000,5000,10000,20000,50000], personalDev:["+1 STR","+1 DEX","+1 END","Melee Combat","Bribery","Gambling"], service:["Streetwise","Mechanics","Gun Combat","Melee Combat","Recon","Vehicle"], specialist:["Computer","Electronics","Bribery","Broker","Recon","Vehicle"], advEdu:["Computer","Gravitics","Jack o' Trades","Medicine","Advocate","Tactics"], medicalBills:[0, 0.5, 0.75] };
var scientist = { name:"Scientist", description:"being a Scientist", qualChar:"EDU", qualTarget:6, surviveChar:"EDU", surviveTarget:5, commissionChar:"INT", commissionTarget:7, advanceChar:"INT", advanceTarget:6, reenlist:5, ranks:["Instructor","Adjunct Professor","Research Professor","Assistant Professor","Associate Professor","Professor","Distinguished Professor"], rankSkills:["Sciences","","","Computer","","",""], benefits:["Low Passage","+1 EDU","+1 INT","Mid Passage","+1 SOC","High Passage","Research Vessel"], cash:[1000,5000,10000,10000,20000,50000,50000], personalDev:["+1 STR","+1 DEX","+1 END","+1 INT","+1 EDU","Gun Combat"], service:["Admin","Computer","Electronics","Medicine","Bribery","Sciences"], specialist:["Navigation","Admin","Sciences","Sciences","Animals","Vehicle"], advEdu:["Advocate","Computer","Jack o' Trades","Linguistics","Medicine","Sciences"], medicalBills:[0.50, 0.75, 1] };
var scout = { name:"Scout", description:"the Interstellar Scout Service", qualChar:"INT", qualTarget:6, surviveChar:"END", surviveTarget:7, commissionChar:"", commissionTarget:0, advanceChar:"", advanceTarget:0, reenlist:6, ranks:["Scout","","","","","",""], rankSkills:["Piloting","","","","","",""], benefits:["Low Passage","+1 EDU","Weapon","Mid Passage","Explorers' Society","Courier Vessel",""], cash:[1000,5000,10000,10000,20000,50000,50000], personalDev:["+1 STR","+1 DEX","+1 END","Jack o' Trades","+1 EDU","Melee Combat"], service:["Comms","Electronics","Gun Combat","Gunnery","Recon","Piloting"], specialist:["Engineering","Gunnery","Demolitions","Navigation","Medicine","Vehicle"], advEdu:["Advocate","Computer","Linguistics","Medicine","Navigation","Tactics"], medicalBills:[0.75, 1, 1] };
var surfaceDef = { name:"Surface Defense", description:"the Surface Defense Service", qualChar:"END", qualTarget:5, surviveChar:"EDU", surviveTarget:5, commissionChar:"END", commissionTarget:6, advanceChar:"EDU", advanceTarget:7, reenlist:5, ranks:["Private","Lieutenant","Captain","Major","Lt Colonel","Colonel","General"], rankSkills:["Gun Combat","","","Leadership","","",""], benefits:["Low Passage","+1 INT","Weapon","Mid Passage","Weapon","High Passage","+1 SOC"], cash:[1000,5000,10000,10000,20000,50000,50000], personalDev:["+1 STR","+1 DEX","+1 END","Athletics","Melee Combat","Vehicle"], service:["Mechanics","Gun Combat","Gunnery","Melee Combat","Recon","Battle Dress"], specialist:["Comms","Demolitions","Gun Combat","Melee Combat","Survival","Vehicle"], advEdu:["Advocate","Computer","Jack o' Trades","Medicine","Leadership","Tactics"], medicalBills:[0.75, 1, 1] };
var technician = { name:"Technician", description:"being a Technician", qualChar:"EDU", qualTarget:6, surviveChar:"DEX", surviveTarget:4, commissionChar:"EDU", commissionTarget:5, advanceChar:"INT", advanceTarget:8, reenlist:5, ranks:["Technician","Team Lead","Supervisor","Manager","Director","Vice-President","Executive Officer"], rankSkills:["Computer","","","","Admin","",""], benefits:["Low Passage","+1 EDU","+1 INT","Mid Passage","Mid Passage","High Passage","+1 SOC"], cash:[1000,5000,10000,10000,20000,50000,50000], personalDev:["+1 STR","+1 DEX","+1 END","+1 INT","+1 EDU","Gun Combat"], service:["Admin","Computer","Mechanics","Medicine","Electronics","Sciences"], specialist:["Computer","Electronics","Gravitics","Linguistics","Engineering","Animals"], advEdu:["Advocate","Computer","Jack o' Trades","Linguistics","Medicine","Sciences"], medicalBills:[0.50, 0.75, 1] };

var availableCareers = [ athlete, aerospaceDef, agent, barbarian, belter, bureaucrat, colonist, diplomat, drifter, entertainer, hunter, marine, maritimeDef, mercenary, merchant, navy, noble, physician, pirate, rogue, scientist, scout, surfaceDef, technician ];
var skillTables = ["personalDev", "service", "specialist", "advEdu"];
var skillTablesNoEdu = ["personalDev", "service", "specialist"];
var skillTablesDescriptions = { personalDev:"Personal Development", service:"Service Skills", specialist:"Specialist Skills", advEdu:"Advanced Education" };
